alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ON_HOURLY_RATE foreign key (HOURLY_RATE_ID) references PETCLINIC_VETERINARIAN(ID);
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ON_PET foreign key (PET_ID) references PETCLINIC_PET(ID);
create index IDX_PETCLINIC_VISIT_ON_HOURLY_RATE on PETCLINIC_VISIT (HOURLY_RATE_ID);
create index IDX_PETCLINIC_VISIT_ON_PET on PETCLINIC_VISIT (PET_ID);
