alter table PETCLINIC_VETERINARIAN add constraint FK_PETCLINIC_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_PETCLINIC_VETERINARIAN_UNIQ_USER_ID on PETCLINIC_VETERINARIAN (USER_ID) ;
create index IDX_PETCLINIC_VETERINARIAN_ON_USER on PETCLINIC_VETERINARIAN (USER_ID);
